services:
    postgres:
        image: postgres:17.0
        container_name: postgres
        environment:
            POSTGRES_PASSWORD: postgrespw
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
#    auctionservice:
#        image: auctionservice
#        build:
#            context: .
#            dockerfile: src/AuctionService/Dockerfile
volumes:
    pgdata:
